Ignore year for adopted documents when base document has defined year
metanorma/pubid-bsi pull request #48
Opened 2024-01-31 14:02 UTC by mico

closes #46

2024-02-06 09:49 UTC, opoudjis requested changes
Not yet:

````
Pubid::Bsi::Identifier.create(number: 639, year: "2013", adopted: Pubid::Cen::Identifier.parse("EN ISO 639:2012")).to_s
````

is giving me `BS EN ISO 639:2012:2013`, not `BS EN ISO 639:2013`. I see that you are removing adopted.year, but it is not having an effect in that case.

2024-02-06 13:41 UTC, ronaldtse commented
Agree with @opoudjis , this is how adoption works, where the year is replaced by the final publishing party.

2024-02-11 09:22 UTC, opoudjis approved these changes

2024-02-11 09:22 UTC, opoudjis commented
@mico Thank you!

2024-02-11 11:23 UTC, merged